
//Post list
export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';
export const RESET_NOTES = 'RESET_NOTES';

//Create new post
export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';
export const RESET_NEW_NOTE = 'RESET_NEW_NOTE';


//Fetch NOTE
export const FETCH_NOTE = 'FETCH_NOTE';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
export const RESET_ACTIVE_NOTE = 'RESET_ACTIVE_NOTE';

//Delete NOTE
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';
export const RESET_DELETED_NOTE = 'RESET_DELETED_NOTE';
